### ISSUE TITLE
Overview: data pre-processing for the tree-based analysis

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/javascript#224]
## Explanation
In order to implement the tree-based analysis, we need to take a few steps to pre-process the necessary data so that it can be easily used by the researches/assessments.

This involves the following steps:
- [ ] Refactor tree folder structure to accomodate metadata https://github.com/Yoast/javascript/issues/119
- [ ] Create `ParsedPaper` class https://github.com/Yoast/javascript/issues/116
- [ ] Create `TreeBuilder` class https://github.com/Yoast/javascript/issues/187
- [ ] Make the current `TreeReseacher` available in the `calculateFor` method of `Research` https://github.com/Yoast/javascript/issues/123
- [ ] Implement Gutenberg tree parser https://github.com/Yoast/javascript/issues/176
- [ ] Add spec for cleanup/calculateTextIndices and cleanup/postParsing https://github.com/Yoast/javascript/issues/195
- [ ] Create a `PaperParser` class https://github.com/Yoast/javascript/issues/188
- [ ] Save morphology data on the webworker https://github.com/Yoast/javascript/issues/121
- [ ] Refactor improved analysis functionality to use `ParsedPaper` instead of `tree` https://github.com/Yoast/javascript/issues/117
- [ ] Fill in `constructMetaData` on the `PaperParser` https://github.com/Yoast/javascript/issues/219
- [ ] Remove `TreeBuilder` class https://github.com/Yoast/javascript/issues/222

Parent https://github.com/Yoast/YoastSEO.js/issues/1903

**Comment by manuelaugustin** [comment]
Closed as all issues in this overview have either been closed or are also on the main overview issue for the text parser.
