### ISSUE TITLE
Create mechanism to register custom tree parser

### ISSUE THREAD

**Issue by atimmer** [Yoast/javascript#398]
## PRs
 - JavaScript: #408 

## Explanation

For Gutenberg we want to transform the knowledge Gutenberg has about the blocks directly into the tree. [This issue has context about the why](https://github.com/Yoast/javascript/issues/176). For this we need a mechanism to register a custom parser.

## Technical decisions

* The result of this task should be to have a function in the analysis library to register a custom parser.
* The function should be available on `this._scope.analysisWorker` exactly like `registerAssessment`. So it can be called from a script loaded using `loadScript`.
* A parser should have a method that decides if the parser is relevant in the current context (Gutenberg, basic HTML, etc.)

## Tasks
 - [ ] Implement method
   - [ ] Add a validation step to check whether the parser is relevant in the current context (e.g., check if there is an `isApplicable` function that returns a boolean)
 - [ ] Add unit tests for registering a (mock) custom parser.
  - [ ] the mock custom parser is a class with an `isApplicable` and a `parse` method
