### ISSUE TITLE
Improve comment processing by the tree parser [Depends on 423]

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#409]
## Explanation

There is a number of examples that show that the current comment-specific functionality does not work perfectly.

#### Example 1
When a comment is followed by a different HTML tag, e.g., `<p>This is a <!--Here is a comment!--><b>paragraph</b></p>`, the `calculateTextIndices` function assigns a wrong `textStartIndex`. Specifically, it does not account for the fact the a number of characters in the source code is taken by the text of the comment.

I suppose that the problem can be solved by adding a currentOffset modification when [comments are being processed](https://github.com/Yoast/javascript/blob/develop/packages/yoastseo/src/parsedPaper/build/tree/cleanup/calculateTextIndices.js#L117:L118). Something like:
```
const commentLength = element.location.endOffset - element.location.startOffset;
currentOffset += commentLength;
```

#### Example 2
When a comment is embedded in a different HTML tag, e.g., `<p>This is a <b><!--Here is a comment!-->paragraph</b></p>`, the parser fails with an error
```
TypeError: Cannot read property 'startOffset' of undefined
```

The problem occurs when the tree builder tries to close the `<b>` tag and checks if all embedded elements have been closed. The comment is cast to an `Ignored` node, which does not have a `location` property, of which the `startOffset` gets called.

We need to revisit creation of `Ignored` nodes for comments and make sure the tree builder does not throw errors.

## Tasks
_The following tasks were identified based on the context we had before finding and solving issue https://github.com/Yoast/javascript/issues/423. They might change substantially when that issue is fixed._

Example 1
- [ ] Debug -> find a fix (start in `treeAdapter`; for a use case see the failing `calculateTextIndices.js`)
- [ ] Implement a fix
- [ ] Switch unit tests on

Example 2
- [ ] The ignored node for comments should get a location. 
- [ ] Switch unit tests on

**Comment by atimmer** [comment]
This is not as easy to solve as I expected. Branch `409-improve-tree-comment-processing` has the work I've tried. You can see the changes in this draft PR: https://github.com/Yoast/javascript/pull/421/files. The problem is that parse5 assumes that the formatting elements (`<strong>`, `<em>`, etc) are also in the tree like normal. This is not the case in our TreeAdapter, because we put them in a flat structure. Then the location info add-on of parse5 crashes. This is the error I tried to solve here: https://github.com/Yoast/javascript/pull/421/files#diff-3c59e9a44f027f2ee3777c540c30e101R443.

But that results in parse5 thinking that the text right after the comment is part of the comment. And then the index of the closing `</b>` tag is all wrong.

I propose the following solution:
* Refactor the current code to not make the flat structure until parse5 is completely done.
* Do this by temporarily saving the tree for the formatting on the text container.
* Do a pass afterwards converting the structured tree inside the text container into the flat structure we desire.

**Comment by hansjovis** [comment]
> * Refactor the current code to not make the flat structure until parse5 is completely done.
> * Do this by temporarily saving the tree for the formatting on the text container.
> * Do a pass afterwards converting the structured tree inside the text container into the flat structure we desire.

I agree. 

We already do a second pass over the tree to e.g. remove location properties that `parse5` expects while parsing, but we do not need. I think it makes sense to add this 'flatten' step to this clean-up phase as well.

**Comment by nataliashitova** [comment]
I've created a separate issue https://github.com/Yoast/javascript/issues/423 to refactor the TreeParser. The current issue will need to be revisited after that issue is solved. Because we don't know how relevant the draft PR of @atimmer will be after the refactoring, I am moving this issue back to the backlog.

**Comment by nataliashitova** [comment]
This issue is possibly solved by #423. It should be closed if so. Otherwise, estimated later.

**Comment by igorschoester** [comment]
Indeed solved through #423 -- closing
