### ISSUE TITLE
Use babel-preset-env using @yoast/browserslist-config (dropping IE11 support)

### ISSUE THREAD

**Issue by atimmer** [Yoast/javascript#411]
## Explanation

All packages should use `babel-preset-env` in combination with the `@yoast/browserslist-config` package. For this two things needs to happen:

* In the `.babelrc` we need to configure babel to use two presets: `react` & `env`.
* In the `package.json` the browserslist needs to be configured using `extends`. [Instructions are in the README.md of the @yoast/browserslist-config package](https://github.com/Yoast/javascript/tree/develop/packages/browserslist-config)

## Technical decisions

An example `.babelrc`:

```json
{
	"presets": [
		"env"
		"react"
	],
	"env": {
		"test": {
			"plugins": [
				"babel-plugin-styled-components"
			]
		}
	}
}
```

## Tasks
_Pair on this issue! Then CR/acceptance are superfluous._
- [ ] Execute the above steps for all JavaScript monorepo packages
- [ ] Testing
  - [ ] Check babel output (`prepublishOnly`) -> Make sure that the relevant JavaScript isn't transpiled anymore: class syntax shouldn't be transpiled; `import` and `export` should still be transpiled
- [ ] Notify QA to specifically test this issue in all supported browsers (and make sure IE11 is DEAD!)
