### ISSUE TITLE
Refactor the HTML TreeAdapter to save formatting elements in a tree structure, not flat

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#423]
## PR
https://github.com/Yoast/javascript/pull/430

## Explanation

In the current implementation of the TreeAdapter for the tree parser, we add all `FormattingElements` as a flat list on the relevant `LeafNode`.

This is justified for the way we plan to use this information, but not compatible with the `parse5` library which [requires a proper tree structure](https://github.com/Yoast/javascript/issues/409#issuecomment-564001774) of `FormattingElements` to be able to build the tree representation of the whole text.

## Tasks
- [ ] Verify that `parse5` works without a TreeAdapter and returns a tree of formatting elements.
- [ ] Use the `parse5` without a TreeAdapter to build the tree from source HTML
- [ ] Convert the output of `parse5` to the output we need for the analysis
    - Ignore comments, styles and scripts
	- After the conversion, tree should use the following structure:
```
Paragraph / Heading
- TextContainer
	- {Text of the paragraph}
	- Formatting
		- bold
		- emphasis
	    - ...
```
- [ ] Adjust unit tests to remove ignored nodes
- [ ] Make sure the unit tests cover comments and embedded elements
- [ ] Add a test for a full text to check the parsed structure
- [ ] Check if the issue https://github.com/Yoast/javascript/issues/409 is solved by your PR.

**Comment by nataliashitova** [comment]
Please test code blocks also (see https://github.com/Yoast/javascript/issues/427)
