### ISSUE TITLE
Create a links statistics research that works with the tree

### ISSUE THREAD

**Issue by nataliashitova** [Yoast/javascript#426]
## Explanation

We need to create a new linksStatistics research that extracts FormattingElements from leafNodes of the input tree, collects all links ('type' = 'a') and checks based on the attributes of the link formattingElement if the link is internal or external, follow or no-follow. The research should return references to the links formattingElements organized in the same data structure as `/yoastseo/src/researches/getLinkStatistics.js`.

## Example of a result
```
[		
		ResearchedLink{ 
			formattingElement: FormattingElement (ref),
			target: "internal"/"external"/"other",
			follow: true/false,
        },
        ...
];
```

## Tasks
- [x] `CalculateFor`:
	- [x] Collect links from the tree in a data structure
	- [x] Assign `target` and `follow` attributes
- [x] `MergeChildren`: concatenate the arrays
- [x] Move the method `isLeafNode` from the `Headings` research to `Research` to make this behaviour default.
- [x] Add unit tests + adjust the Research spec.
