### ISSUE TITLE
Create Facebook preview modal 

### ISSUE THREAD

**Issue by andizer** [Yoast/javascript#444]
This modal should reflect the entire facebook preview:
- The facebook share preview (See #47) 
- The form for managing the facebook data (See #443) 

Both objects should be tied together with the Redux store, see #440 

Example of the modal: https://sketch.cloud/s/oVPZY/a/vnv8gb/play

The modal should have:
- [ ] A title with Yoast logo
- [ ] The form on the left side
- [ ] The preview on the right side
- [ ] On the bottom (aligned to the right) the next two actions:
   - [ ] A purple button that saves the changes
   - [ ] A blue link that cancels (closes the model)

**Note**: we should take care of responsive views and make sure it works fine on lower resolutions. Maybe mobile as well. To make it responsive we can show the form below the preview.

**Comment by bintzandt** [comment]
This modal is replaced by a new modal. We will create new issues for this.
