### ISSUE TITLE
Create action and selector for FacebookDescription

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#465]
Parent https://github.com/Yoast/javascript/issues/440

## Explanation
Create an action and a selector that will set / retrieve the `FacebookDescription` value from the Redux store.

For more information about Redux (and the store), see: https://redux.js.org/api/store/.

## Tasks
- [ ] Create an action that will set the value for `FacebookDescription`
- [ ] Create a selector that retrieves the value for the `FacebookDescription`
	- [ ] If the value isn't set we should return one of the 'fallback' values (meta description, post excerpt/taxonomy description, side wide default).
