### ISSUE TITLE
Create Redux store for the twitter previews

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#468]
Children #470, #471, #472, #473

This issue is split in several sub-issues. This issue serves as an overview of those issues and has two (simple) tasks itself.

We have to create a Redux store for storing the data entered in the Twitter previews. The store should contain values for:
* TwitterTitle (#44)
* TwitterDescription (#49)
* TwitterImage (#50)
* TwitterImageType (landscape, portrait or square)
* TwitterSiteName (static value) (#43)

### Reducer
The reducers for the Twitter preview should have the following state:
```
INITIAL_STATE = {
	twitter: {
	    title: "",
	    description: "",
	    imageUrl: "",
		imageId: "",
	    siteName: "",
		errors: [],
	}
}
```

Make sure the reducer handles everything.

### Actions
- [ ] Create an action that will set the value for `TwitterTitle`
- [ ] Create an action that will set the value for `TwitterDescription`
- [ ] Create an action that will set the value for `TwitterImage`
- [ ] Create an action that will set the value for `TwitterImageType`. This depends on the dimensions of the used image.

### Selectors
All selectors have a fallback to the values from the Facebook preview if they have been entered.

- [ ] Create a selector that retrieves the value for the `TwitterTitle`.
	- If the value is not set but the `FacebookTitle` is, return `FacebookTitle`. Otherwise,
   	- If the value isn't set we should return one of the 'fallback' values (snippet preview, post title, site wide default). 
- [ ] Create a selector that retrieves the value for the `TwitterDescription`.
	- If the value is not set but the `FacebookDescription` is, return `FacebookDescription`. Otherwise,
   	- If the value isn't set we should return one of the 'fallback' values (meta description, post excerpt/taxonomy description, side wide default).
- [ ] Create a selector that retrieves the value for the `TwitterImage`. 
	- If the value is not set but the `FacebookImage` is, return `FacebookImage`. Otherwise,
	- If the value isn't set we should return one of the 'fallback' values (featured image, content image, side wide default).
- [ ] Create a selector that retrieves the value for the `TwitterImageType`. The values depends on the dimension of `TwitterImage`.
	- If the value is not set but the `FacebookImage` is, return the type of `FacebookImage`

### Tasks
- [ ] Create a selector that retrieves the value for the `TwitterSiteName`. This should return the value that is set by localization. This is a static value that can't be changed.

**Comment by maartenleenders** [comment]
Verify if fixed in https://github.com/Yoast/javascript/issues/440

**Comment by GuidoOffermans** [comment]
fixed in #440
