### ISSUE TITLE
Create action and selector for TwitterTitle

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#470]
Parent #468 

## Explanation
Create an action and a selector that will set / retrieve the `TwitterTitle` value from the Redux store.

For more information about Redux (and the store), see: https://redux.js.org/api/store/.

## Tasks
- [ ] Create an action that will set the value for `TwitterTitle`
- [ ] Create a selector that retrieves the value for the `TwitterTitle`
	- [ ] If the value isn't set and the Facebook Preview is enabled, return the value of `FacebookTitle`.
	- [ ] If the value isn't set we should return one of the 'fallback' values (snippet preview, post title, site wide default).
