### ISSUE TITLE
Create action and selector for TwitterDescription

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#471]
Parent #468 

## Explanation
Create an action and a selector that will set / retrieve the `TwitterDescription` value from the Redux store.

For more information about Redux (and the store), see: https://redux.js.org/api/store/.

## Tasks
- [ ] Create an action that will set the value for `TwitterDescription`
- [ ] Create a selector that retrieves the value for the `TwitterDescription`
	- [ ] If the value isn't set and the Facebook Preview is enabled, return the value of `FacebookDescription`.
	- [ ] If the value isn't set we should return one of the 'fallback' values (meta description, post excerpt/taxonomy description, side wide default).
