### ISSUE TITLE
Create action and selector for TwitterImage

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#472]
Parent #468 

## Explanation
Create an action and a selector that will set / retrieve the `TwitterImage` value from the Redux store.

For more information about Redux (and the store), see: https://redux.js.org/api/store/.

## Tasks
- [ ] Create an action that will set the value for `TwitterImage`
- [ ] Create a selector that retrieves the value for the `TwitterImage`
	- [ ] If the value isn't set and the Facebook Preview is enabled, return the value of `FacebookImage`.
	- [ ] If the value isn't set we should return one of the 'fallback' values (featured image, content image, side wide default).
