### ISSUE TITLE
Create action and selector for TwitterImageType

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#473]
Parent #468 

## Explanation
Create an action and a selector that will set / retrieve the `TwitterImageType` value from the Redux store.

For more information about Redux (and the store), see: https://redux.js.org/api/store/.

## Tasks
- [ ] Create an action that will set the value for `TwitterImageType`
- [ ] Create a selector that retrieves the value for the `TwitterImageType`
	- [ ] If the value isn't set and the Facebook Preview is enabled, return the value of `FacebookImageType`.
	- [ ] If the value is not set but the FacebookImage is, return the type of `FacebookImage`.
