### ISSUE TITLE
Create FacebookPreview container

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#475]
Relates https://github.com/Yoast/javascript/issues/45 (the FacebookPreview component)

## Explanation
This container needs to fetch all the data needed from the redux store and provide it to the FacebookPreview component. This ensures that we can keep the FacebookPreview component as minimal as possible and make it possible to reuse the component in other places.

## Technical decisions
See https://medium.com/@learnreact/container-components-c0e67432e005 for explanation about containers.

## Tasks
- [ ] Fetch all data from the store using the selectors created in #440 
	- [ ] `title`
	- [ ] `description`
	- [ ] `image`
	- [ ] `imageType`
	- [ ] `siteName`
- [ ] **[optional]** Modify the data so that it has the correct format. Be sure to think about whether it might be better to change the data in the store before doing this.
- [ ] Provide the data to the component
