### ISSUE TITLE
Update the ReplacementVariableEditor

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#487]
## Explanation

Because we want to use the editor in other places besides the snippet editor, we need to make some changes to the component.

## Technical decisions

The defaults should be kept the same so that the component does not change in the Snippet Editor.

For the design see https://sketch.cloud/s/2Zz4p/a/ZoZjAp.

## Tasks
- [x] Update the `propTypes` so that all props that need to be set are eiter
	* Marked as required
	* Have a default props declaration
- [x] Change the name of the `Insert snippet variable` button to `Insert variable`.
- [x] Remove the `Plus` SVG icon.
- [x] Change the styles of the button. There is a new design and the styles should be updated to reflect this.
- [ ] Style `ImageUpload.js` so it matches the styling in https://sketch.cloud/s/2Zz4p/a/ZoZjAp.
- [ ] Keep the component backwards compatible.

**Comment by bintzandt** [comment]
I have created a PR that addresses some of the Tasks defined in this issue. However, I cannot complete this PR until other PRs are merged.

Specifically, the `ImageUpload.js` component cannot be styled until it is merged in the feature branch.

There are also some issues regarding the design of the components. I have asked Tim if he has specific styling for me but he has not yet replied.
