### ISSUE TITLE
Extract ReplacementVariableEditor to a separate package

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#505]
## Explanation
The ReplacementVariableEditor is being used on its own outside of the search-metadata-previews package (e.g. in the Social Preview forms). As it is a perfectly functioning stand-alone component with complementary helper functions, we'd like to extract it to a separate package.

## Technical decisions

ReplacementVariableEditor should still be made available through the  search-metadata-previews package, by importing it into the index of that package, and exporting it there as well (to guarantee backward compatibility).

## Tasks:

- [x] Create a new package with a package.json.
- [x] Update the repo's README.md.
- [x] Select helper functions that are ReplacementVariableEditor specific  from the Helpers folder, and move them to the new package.
- [x] Remove implementation specific logic from the ReplacementVariableEditor, like the switch for the InputContainer being the TitleInputContainer or the DescriptionInputContainer, if needed (I can't really oversee how implementation specific this is, all that changes is some CSS). There probably needs to be some logic in the search-metadata-previews to implement the more abstracted ReplacementEditor from the new package.
- [x] Take care of backward compatibility by importing the new package in the index of `search-metadata-previews` and exporting it there too.
- [x] Always be mindful of the reusability of any code that you move, if that code was exported by `search-metadata-previews`. Apparently there is a [tool](https://wpdirectory.net/) that allows you to search whether any code is used in Wordpress by other plugins. If a function you move is exported, very reusable (and not specific to replacementvariable editors), it's probably wise to export it from the search previews index again.
- [x] Make sure the Google preview is still working correctly after this change.
- [x] Make sure the Search appearance pages are still working correctly after this change.
- [ ] Notify Plugin 2 that a new package is coming to prevent surprises during monorepo releases.
- [x] Create an issue on Free to update the imports to reflect the new packages structure (see https://github.com/Yoast/wordpress-seo/issues/14422)

## Feedback?
Discussed with @atimmer 
@IreneStr

**Comment by bintzandt** [comment]
Plugin 2 has not been notified yet. The plan is to do that when https://github.com/Yoast/javascript/issues/506 is also finished so that we do not have to bother them too much.
