### ISSUE TITLE
Move Social Preview forms to separate package

### ISSUE THREAD

**Issue by maartenleenders** [Yoast/javascript#506]
## Explanation and Technical Decisions
We want to move the SocialMetadataPreviewForms to their own package, so that they can be included in Free, separately from the Previews, which should be in Premium.

I think it is best to do this after https://github.com/Yoast/javascript/issues/505 is merged, so that you can also point to the new ReplacementVariableEditor package, but it is not a blocker per se.

## Tasks
- [ ] If it hasn't already done yet, merge `develop` into the feature branch to get the changes from #505 
- [ ] Move social metadatapreview forms and imageselect to a new package.
- [ ] If https://github.com/Yoast/javascript/issues/505 is already merged, point to the new ReplacementVariableEditor package.
- [ ] Notify Plugin 2 that a new package is coming to prevent surprises during monorepo releases.

## Feedback?
Discussed with @atimmer and @Xyfi 
@IreneStr
