### ISSUE TITLE
Create TextInput and TextArea inputs

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#558]
Parent #550

## Explanation
Team Front-end has provided us with loads of CSS and HTML files that we can use to create React components.

This issue relates to the input components.

## Tasks
- [x] Create a React component from the HTML
- [x] Write tests for the component
- [x] Add the new component to the `Reactification` tab in the example components app
- [x] Update snapshots for the example app
- [x] Make sure `eslint` is OK
