### ISSUE TITLE
Create RadioButton Component

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#559]
Parent #550

## Explanation
Team Front-end has provided us with loads of CSS and HTML files that we can use to create React components.

This issue relates to the RadioButton component.

## Tasks
- [ ] Create a React component from the HTML
- [ ] Write tests for the component
- [ ] Add the new component to the `Reactification` tab in the example components app
- [ ] Update snapshots for the example app
- [ ] Make sure `eslint` is OK
