### ISSUE TITLE
Create Select component

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#560]
Parent #550

## Technical decisions
We are going to use the `select2` package in all the places where we are currently using it. This means that we will have to create 2/3 React components:
- A select for the normal use case
- A select for `multiple="multiple"`
- A select for when the `select2` package is used

Depending on the implementation, the first two can be taken together in a single React component.

## Explanation
Team Front-end has provided us with loads of CSS and HTML files that we can use to create React components.

This issue relates to the Select component.

## Tasks
- [ ] Create a React component from the HTML
- [ ] Write tests for the component
- [ ] Add the new component to the `Reactification` tab in the example components app
- [ ] Update snapshots for the example app
- [ ] Make sure `eslint` is OK

**Comment by bintzandt** [comment]
@JoseeWouters could you please comment on whether we still want to use `Select2`? And what we are going to do with `<select multiple="multiple">`?
