### ISSUE TITLE
Create Checkbox component

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#564]
Parent #550

## Explanation
Team Front-end has provided us with loads of CSS and HTML files that we can use to create React components.

This issue relates to the Checkbox component.

## Tasks
- [x] Create React components from the HTML
- [x] Write tests for the components
- [x] Add the new component to the `Reactification` tab in the example components app
- [x] Update snapshots for the example app
- [x] Make sure `eslint` is OK
