### ISSUE TITLE
Create DataModel component

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#565]
Parent #550

## Explanation
Team Front-end has provided us with loads of CSS and HTML files that we can use to create React components.

This issue relates to the DataModel component.

## Tasks
- [ ] Double-check with team frontend about the usecase for this component
- [ ] Create React components from the HTML
- [ ] Write tests for the components
- [ ] Add the new component to the `Reactification` tab in the example components app
- [x] Update snapshots for the example app
- [x] Make sure `eslint` is OK
- [x] If you come up with a better name, please change the issue and the component accordingly.

**Comment by bintzandt** [comment]
I have checked with @JoseeWouters. She gave me [a link to where this component will be used](https://sketch.cloud/s/r0zwq/a/gw4Kgd). It seems like that is the only location. Let's create the component. If it turns out that we can do without the component and simply use it's styling on a list, we can always change that 👍
