### ISSUE TITLE
Create Modal component

### ISSUE THREAD

**Issue by bintzandt** [Yoast/javascript#566]
Parent #550

## Explanation
A desktop modal already exists in our codebase. Please check if it matches the specifications.

The breakpoint for mobile / desktop view is `782px`.

Depending on the breakpoint, either render the `MobileModal` component or the `DesktopModal` component.

This can be done in the `Modal` component.

## Tasks
- [ ] Check the impact of making changes in the current modal and discuss this with UX (and maybe Jessie for the planning)
- [ ] Remove styled-components from the Modal and add class-names (see front-end's HTML)
- [ ] Create the `MobileModal` component (see HTML)
- [ ] Create a wrapper modal that conditionally renders one of the modals. This is based on the breakpoint of `782px`
- [ ] Update/write tests for the components
- [ ] Don't forget the example app (snapshots, etc.)

**Comment by IreneStr** [comment]
This issue has been moved to Jira: https://yoast.atlassian.net/browse/P1-9
